image:
  repository: ghcr.io/marokos999/cloudcart-gateway
  tag: "latest"

service:
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  host: "cloudcart.local"
  path: "/"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

env:
  - name: ASPNETCORE_ENVIRONMENT
    value: "Development"
