image:
  repository: ghcr.io/marokos999/cloudcart-inventory
  tag: "latest"

service:
  port: 80
  targetPort: 8080

env:
  - name: ASPNETCORE_ENVIRONMENT
    value: "Development"
  - name: ConnectionStrings__Database
    value: "Server=mssql-inventory;Database=InventoryDb;User Id=sa;Password=Password@123;TrustServerCertificate=True;"
  - name: MessageBroker__Host
    value: "amqp://rabbitmq:5672"
  - name: MessageBroker__UserName
    value: "guest"
  - name: MessageBroker__Password
    value: "guest"
